package com.techdegree.instateam.model;

import javax.persistence.*;
import javax.validation.constraints.Pattern;

@Entity
@Table(name = "collaborators")
public class Collaborator {
    // primary id field, column, autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private int id;

    // name alphanumeric VARCHAR, has pattern, message, can be null? I think
    // regex takes care for that
    // same as name in Role class
    @Column(name = "NAME", columnDefinition = "VARCHAR")
    @Pattern(regexp = "\\s*[a-zA-Z0-9]+(\\s+[a-zA-Z0-9]+)*\\s*",
        message = "Name must consist of alphanumeric characters: a-Z, 0-9")
    private String name;

    // relation to role class, Many Collaborators can have one Role
    // role removal detaches collaborators. Collaborators will get NULL
    // in their role_id primary key, see `RoleDaoImpl.delete` method for more
    @ManyToOne(cascade = CascadeType.DETACH)
    private Role role;

    // getters and setters

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Role getRole() {
        return role;
    }
    public void setRole(Role role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Collaborator that = (Collaborator) o;

        if (id != that.id) return false;
        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        return role != null ? role.equals(that.role) : that.role == null;

    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (role != null ? role.hashCode() : 0);
        return result;
    }

    public Collaborator() {
        // default constructor for JPA
    }
}
